# Generated by Django 5.2.5 on 2025-08-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Назва гри')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL гри')),
                ('platform', models.CharField(choices=[('PC', 'Computer'), ('PS5', 'Play Station 5'), ('PS4', 'Play Station 4'), ('XBOX', 'XBOX'), ('SWITCH', 'Nintendo Switch')], verbose_name='Платформа')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр гри')),
                ('rating', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, default='default_image.png', upload_to='images/game_image', verbose_name='Картинка гри')),
                ('description', models.TextField(verbose_name='Опис гри')),
                ('developer', models.CharField(blank=True, max_length=150, verbose_name='Розробник')),
                ('publisher', models.CharField(blank=True, max_length=150, verbose_name='Видавець')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Гра',
                'verbose_name_plural': 'Ігри',
                'ordering': ['-title'],
            },
        ),
    ]
