# Generated by Django 5.2.5 on 2025-08-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', upload_to='game_images/', verbose_name='Картинка гри'),
        ),
    ]
