# Generated by Django 5.2.5 on 2025-08-31 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('Difficult', 'Складно'), ('Medium', 'Середньо'), ('Easy', 'Легко')], default='Medium', max_length=10, verbose_name='Складність досягнень'),
        ),
    ]
