# Generated by Django 5.2.5 on 2025-08-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PC', 'Computer'), ('PS5', 'Play Station 5'), ('PS4', 'Play Station 4'), ('XBOX', 'XBOX'), ('SWITCH', 'Nintendo Switch')], max_length=20, unique=True, verbose_name='Платформа')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформи',
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(to='games.platform', verbose_name='Платформа'),
        ),
    ]
