# Generated by Django 5.2.5 on 2025-10-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_platform_remove_game_platform_game_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(related_name='games', to='games.platform', verbose_name='Платформа'),
        ),
    ]
